namespace FluxorExperiments.ClassLibrary.PlainTextEditor;

public record struct PlainTextTokenMetaData(PlainTextTokenBase PlainTextToken,
	PositionSpanRelativeToRowRecord? PositionSpanRelativeToRowRecord,
	PositionSpanRelativeToDocumentRecord? PositionSpanRelativeToDocumentRecord);