using FluxorExperiments.ClassLibrary.Clipboard;
using FluxorExperiments.ClassLibrary.KeyDownEvent;

namespace FluxorExperiments.ClassLibrary.Store.PlainTextEditor;

public record PlainTextEditorKeyDownEventAction(KeyDownEventRecord KeyDownEventRecord, IClipboardProvider ClipboardProvider);